BaseURL = "http://ellasworld.site/"
LanguageCode = "en-US"
HasCJKLanguage = true
Title = "Ella's World"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
# RSSUri = "feed.xml"

[Author]
  Name = "Ella"

[Params]
#  AuthorHomepage = "http://blog.coderzh.com"
# BottomIntroduce = "Click the porpoise!"#  <br/> Introduce2"
 Description = ""
 Subtitle = "Hi I'm Ella.  I'm 9 years old and live in Perth, Australia."
#  Weibo = "coderzh"
#  WeiboID = 1816308191
#  Twitter = "coderzh"
#  GitHub = "coderzh"
#  Facebook = "coderzh"
#  LinkIn = "coderzh"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/porpoise.png"
  DateFormat = "2006/01/02"
  MonthFormat = "2006/01"
  FancyBox = true

  #[Params.DuoShuo]
  #  ShortName = "coderzh"

  #[Params.Disqus]
  #  ShortName = "coderzh"

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Strings]
    # Search = "Search"
    # PageNotFound = "你访问的页面不存在"
    # ShowSideBar = "显示侧边栏"
    # HideSideBar = "隐藏侧边栏"
    # Categories = "分类"
     Archive = "Archive"
     Tags = "Tags"
    # TagCloud = "标签云"
    # Rss = "RSS 订阅"
    # TableOfContents = "文章目录"

 [Menu]
#   [[Menu.Main]]
#    Name = "首页"
#    URL = "/"
#    Weight = 1
  [[Menu.Main]]
    Name = "About Me"
    URL = "/about"
    Weight = 2
